// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_rRh5UMICCOuqloR0PapWeEfPkDSbDA',
    appId: '1:728795550154:web:1c02007021cd83b7087f33',
    messagingSenderId: '728795550154',
    projectId: 'userapp-ee140',
    authDomain: 'userapp-ee140.firebaseapp.com',
    storageBucket: 'userapp-ee140.appspot.com',
    measurementId: 'G-Y6TQQ220V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPtZrE32ylv7go8xUGoGxdVVtk2G7ZchA',
    appId: '1:728795550154:android:779ee770338c26e8087f33',
    messagingSenderId: '728795550154',
    projectId: 'userapp-ee140',
    storageBucket: 'userapp-ee140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Op5Y8JSocSZwJarSEJHZDqQ05m9FuwY',
    appId: '1:728795550154:ios:bdcc36d995f5e1b2087f33',
    messagingSenderId: '728795550154',
    projectId: 'userapp-ee140',
    storageBucket: 'userapp-ee140.appspot.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Op5Y8JSocSZwJarSEJHZDqQ05m9FuwY',
    appId: '1:728795550154:ios:2bf40e027874984e087f33',
    messagingSenderId: '728795550154',
    projectId: 'userapp-ee140',
    storageBucket: 'userapp-ee140.appspot.com',
    iosBundleId: 'com.example.userapp.RunnerTests',
  );
}
